#define COL_BLACK	0
#define COL_BLUE	1
#define COL_GREEN	2
#define COL_CYAN	3
#define COL_RED		4
#define COL_MAGENTA	5
#define COL_BROWN	6
#define COL_LIGHTGRAY	7
#define COL_DARKGRAY	8
#define COL_LIGHTBLUE	9
#define COL_LIGHGREEN	10
#define COL_LIGHTCYAN	11
#define COL_LIGHTRED	12
#define COL_LIGHMAGENTA	13
#define COL_YELLOW	14
#define COL_WHITE	15
