-- Active: 1647365195286@@127.0.0.1@3306@mydb
INSERT INTO Critico VALUES
(1,NULL,'Richard','Corliss'),
(2,NULL,'Edwars','Guthmann'),
(3,NULL,'Mike','Clark'),
(4,NULL,'Roger','Ebert'),
(5,NULL,'James','Beraldinelli'),
(6,NULL,'Owen','Gleiberman'),
(7,NULL,'Jonathan','Rosenbaum'),
(8,NULL,'John','Harti'),
(9,NULL,'Peter','Travers'),
(10,NULL,'Rita','Kempley'),
(11,NULL,'Mark','Johnson'),
(12,NULL,'Brian','Eggert'),
(13,NULL,'Wilson Ward','Marsh'),
(14,NULL,'Alex','Maidy'),
(15,NULL,'Tom','Meek'),
(16,NULL,'Joanne','Laurier'),
(17,NULL,'Mike','Massie'),
(18,NULL,'Otis','Stuart'),
(19,NULL,'Matt','Neal'),
(20,NULL,'Micheal','Wilmington'),
(21,NULL,'Lou','Lumenick'),
(22,NULL,'Kate','Cameron'),
(23,NULL,'Cath','Clarke'),
(24,NULL,'David','Denby'),
(25,NULL,'Jeremiah','Kipp'),
(26,NULL,'James','Beradinelli'),
(27,NULL,'Serena','Donadoni'),
(28,NULL,'Pauline','Kael'),
(29,NULL,'David','Parkinson'),
(30,NULL,'Martyn','Conterio'),
(31,NULL,'Kenneth','Turan'),
(32,NULL,'Peter','Brandshaw'),
(33,NULL,'Dave','Kehr'),
(34,NULL,'Shawn','Levy'),
(35,NULL,'David','Edelstein'),
(36,NULL,'David','Sterrit');


INSERT INTO Voto_Critico VALUES
(7,1,80,'A long drink of water at the fountain of pop-social memory.'),
(7,2,75,'At its best, Forrest Gump is a gentle, elegiac fantasy about love and trust.'),
(7,3,88,'It does not sound like a very prepossessing title, but prepare to be taken aback by -what is in a name-'),
(7,4,100,'What a magical movie'),
(7,5,100,'Passionate and magical, Forrest Gump is a tonic for the weary of spirit.'),
(7,6,50,'It is also glib, shallow, and monotonous, a movie that spends so much time sanctifying its hero that, despite his "innocence," he ends up seeming about as vulnerable as Superman'),
(7,7,90,'The results are skillful, highly affecting, and ultimately more than a little pernicious'),
(7,8,90,'This is an ambitious movie that attempts too much rather than too little'),
(7,9,90,'A movie heart-breaker of oddball wit and startling grace.'),
(7,10,90,'Zemeckis, an undisputed master of film technology, shows off an equal aptitude for vivid storytelling.'),
(7,11,70,'It is most successful when it is being off-center, a state of grace it does not quite have the nerve to maintain.'),
(1,12,80,'It remains the most seen film in cinema history, not only because Selznick produced a monumental motion picture of immaculate quality, but because he knew how to sell it as an event.'),
(1,13,65,' Dubbed the “Golden Year of Cinema,” 1939 is often cited as the greatest year in the history of film. Five movies from 1939 made the original American Film Institute’s Top 100 Films list. Many of these movies hold up extraordinarily well, but none more stunningly than Victor Fleming’s Gone with the Wind. Vivien Leigh and Clark Gable star as the southern belle and her wily and charismatic love interest, set amongst the backdrop of the antebellum South as the Confederacy meets its ruin. The performances, set designs, costumes, Technicolor photography, and Max Steiner’s exhilarating score keep this film as bewildering and extravagant a film today as it ever was.
What it beat: Dark Victory, Goodbye Mr. Chips, Love Affair, Mr. Smith Goes to Washington, Ninotchka, Of Mice and Men, Stagecoach, The Wizard of Oz, Wuthering Heights
Hindsight is a bitch: The lunacy of this era can be summarized with the way Gone with the Wind – long thought of as one of the two or three greatest American films – has attained a patina of disrepute for the way it depicted black characters and romanticized the South at the time. The time of the film, of course, being the Civil War, for Christ’s sake. But I digress from such asinine and irresponsible revisionist politics that choose to sterilize our history rather than take the complicated and nuanced approach of studying it for what it was. While I would not argue against The Wizard of Oz, the Academy got it correct.'),
(1,14,50,'Gone With The Wind is a woefully overrated film that takes a revisionist look at the Civil War as a romantic era rather than a violent and racist period of American history. Couple that with characters who are so poorly conceived and melodramatically acted and you are left with a film that never manages to be more than a curiosity from a bygone era. As a movie regarded as one of the greatest of all time, it is a painful reminder of how tone-deaf Hollywood can be in the pursuit of making popular films. Gone With The Wind is an expertly manufactured work that checks off every requirement of a studio executive rather than serving as an inspirational film worth any level of emotional investment. If you love it, then fiddle-dee-dee because I do not give a damn.'),
(1,15,75,'One of the early films that would make de Havilland a household name and even has an uncredited (and unused – or so it is said) early contribution from F. Scott Fitzgerald, is now under cultural scrutiny for its romanticizing of the slave-owning South. The film, directed by Victor Fleming (after George Cukor was fired) is a gorgeous production from an aesthetic and technical standpoint. One of the first technicolor films made by Hollywood, the panning shot of injured and dead soldiers littering a street remains unforgettable. The casting of Scarlett (Vivien Leigh) and Rhett (Clark Gable) remains iconic, even as the film comes under questions of intent and embrace. Context and reflection are necessary and important when sitting down to re-screen.'),
(1,16,75,'One of the early films that would make de Havilland a household name and even has an uncredited (and unused – or so it is said) early contribution from F. Scott Fitzgerald, is now under cultural scrutiny for its romanticizing of the slave-owning South. The film, directed by Victor Fleming (after George Cukor was fired) is a gorgeous production from an aesthetic and technical standpoint. One of the first technicolor films made by Hollywood, the panning shot of injured and dead soldiers littering a street remains unforgettable. The casting of Scarlett (Vivien Leigh) and Rhett (Clark Gable) remains iconic, even as the film comes under questions of intent and embrace. Context and reflection are necessary and important when sitting down to re-screen.'),
(1,17,100,'No other movie has had quite the impact, the influence, or the epic feel (perhaps as only a nearly four-hour-long production could create) of this unmistakable masterpiece'),
(1,18,80,'True to the book, the film of Gone With The Wind is held together by its heroine.'),
(1,19,100,'Hey kids, wanna watch a four-hour-long romantic melodrama, told from the sympathetic perspective of the racist slave owners who lost the Civil War?'),
(1,20,80,'"Gone With the Wind" offers the kind of big, rich, opulent experience the movies are in a unique position to offer but seldom do.'),
(1,21,50,'The film is subtle racism is insidious, going to great lengths to enshrine the myth that the Civil War was not fought over slavery - an institution the film unabashedly romanticizes.'),
(1,22,80,'There has never been a picture like David O. Selznicks production of Gone With the Wind.'),
(1,23,80,'No one watches Gone with the Wind for historical accuracy. What keeps us coming back is four-hours of epic romance in gorgeous Technicolor'),
(2,7,90,'Part of what makes this wartime Hollywood drama (1942) about love and political commitment so fondly remembered is its evocation of a time when the sentiment of this country about certain things appeared to be unified. (It is been suggested that communism is the political involvement that grizzled of Bogart casino owner Rick may be in retreat from at the beginning.) This hastily patched together picture, which started out as a B film, wound up getting an Oscar, and displays a cozy, studio-bound claustrophobia that Howard Hawks improved upon in his superior spin-off To Have and Have Not. '),
(2,24,100,'The most familiar movie in the world is still fresh; it has so many little busy corners to nestle in... Casablanca is the most sociable, the most companionable film ever made. Life as an endless party.'),
(2,25,100,'The film has a peculiar magic to it, and because of its pace the richness of its sense of detail often goes unnoticed.'),
(2,26,100,'Casablanca accomplishes that which only a truly great film can: enveloping the viewer in the story, forging an unbreakable link with the characters, and only letting go with the end credits.'),
(2,27,100,'Casablanca was filmed in the safety of the Warner Bros. lot, but the cast of immigrants and exiles who had fled the Third Reich conveyed their visceral fear. While the future was uncertain, the resolute characters of this exquisite wartime drama found peace through love and resistance.'),
(3,28,50,'Billy Wilder is inane yet moderately entertaining version of an Agatha Christie courtroom thriller, with Charles Laughton wiggling his wattles.'),
(3,29,80,'Marlene Dietrich tries not to give anything away as usual while Agatha Christie is whodunit plot whirs tidily about her expressionless beauty.'),
(3,30,80,'While not amongst the greater, more celebrated titles in Billy Wilder is acclaimed filmography, his big screen adaptation of Agatha Christie’s Witness for the Prosecution boasts a fine, scenery-chewing performance by Charles Laughton, here playing a cantankerous barrister defending a murder suspect.'),
(4,4,100,'The movie is made with boundless energy. Fellini stood here at the dividing point between the neorealism of his earlier films (like "La Strada") and the carnival visuals of his extravagant later ones ("Juliet of the Spirits,","Amarcord")'),
(4,20,100,'One of the true classics.'),
(5,31,100,'Overflowing with life, rich with all the grand emotions and vital juices of existence, up to and including blood. And its deaths, like that of Hotspur in "Henry IV, Part I," continue to shock no matter how often we have watched them coming'),
(5,32,100,'Coppola is epic storytelling sweep is magnificent: there is an electric charge in simply the shift from New York to California to Sicily and back to New York. This is the top-down approach to gangsters, the “great man” theory of organised crime. Later movies such as Scorsese’s Goodfellas will emphasise the more ragged lower ranks'),
(5,26,100,'The picture is a series of mini-climaxes, all building to the devastating, definitive conclusion... It was carefully and painstakingly crafted. Every major character - and more than a few minor ones - is molded into a distinct, complex individual.'),
(6,33,100,'An exhilarating update of "Flash Gordon," very much in the same half-jokey, half-earnest mood, but backed by special effects that, for once, really work and are intelligently integrated with the story.'),
(6,5,100,'Like all great craftsmen, Lucas has managed to fashion this material in a manner that not only honors the original sources, but makes it uniquely his own. Hacks rip off other movies; artists synthesize and pay homage to their inspirations.'),
(6,4,100,'If I were asked to say with certainty which movies will still be widely known a century or two from now, I would list "2001", "The Wizard of Oz", "Keaton and Chaplin", "Astaire and Rogers", and probably "Casablanca" ... and "Star Wars",for sure.'),
(6,10,80,'Star Wars had all the right stuff, and unlike its confounding progenitor, "2001: A Space Odyssey," it was fairy-tale simple: "A long time ago in a galaxy far, far away," good met evil.'),
(8,5,100,'You do not just watch Titanic, you experience it.'),
(8,6,100,'Titanic floods you with elemental passion in a way that invites comparison with the original movie spectacles of D.W. Griffith.'),
(8,3,100,'His (Cameron) movie may not be perfect, but visually and viscerally, it pretty well is.'),
(8,10,100,'A film that sweeps us away into a world of spectacle, beauty and excitement, a realm of fantasy unimaginable without the movies.'),
(8,34,100,'It is quite possible that Titanic is one of the greatest romantic epics ever filmed.'),
(8,7,90,'One hell of a movie.'),
(8,31,30,'What audiences end up with word-wise is a hackneyed, completely derivative copy of old Hollywood romances, a movie that reeks of phoniness and lacks even minimal originality.'),
(8,35,50,'Cameron has never been known for his dialogue, but Titanic carries some stinkers that would not make the final draft of a "Days of Our Lives" script.'),
(9,3,88,'The filmmaker keeps upping the ante with surprises until the plot-twist beaut that concludes the picture - a shocker that, upon reflection, is probably the one ending that would not have fallen a little flat.'),
(9,8,80,'The boy (Osment) has an uncanny ability to suggest secretive of Cole, haunted soul, and he seems to have inspired Willis to give perhaps his most self-effacing performance.'),
(9,4,75,'Has a kind of calm, sneaky self-confidence that allows it to take us down a strange path, intriguingly.'),
(9,35,70,'Ultimately, it has less in common with "Blair Witch" than with such quivering lumps of sentiment as "Ghost" and Field of Dreams."'),
(9,5,38,'An inferior product. It is not well written, well acted, or well directed.'),
(10,1,100,'The second half of the film elevates all the story elements to Beethovenian crescendo. Here is an epic with depth of literature and splendor of opera -- and one that could be achieved only in movies. What could be more terrific?'),
(10,5,100,'Labeling this as a "movie" is almost an injustice. This is an experience of epic scope and grandeur, amazing emotional power, and relentless momentum.'),
(10,31,100,'As completely real on the psychological level as its up-to-the-moment visual effects have on the physical.'),
(10,20,100,'Like all great fantasies and epics, this one leaves you with the sense that its wonders are real, its dreams are palpable.'),
(10,35,100,'It might be the cinema is most astonishing holy war film. The Lord of the Rings took seven years and an army of gifted artists to execute, and the striving of its makers is in every splendid frame. It is more than a movie--it is a gift.'),
(10,4,88,'There is little enough psychological depth anywhere in the films, actually, and they exist mostly as surface, gesture, archetype and spectacle. They do that magnificently well, but one feels at the end that nothing actual and human has been at stake.'),
(10,9,88,'This is a film in which ideas resonate as well as action. Gandalf’s words to Pippin about death have a muscular poetry.'),
(10,36,50,'Add a lot of dull acting -- except Sir Ian McKellen and Andy Serkis -- and you have an uneven movie with yawns aplenty.');
